name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0  # Replace with your Python version

      # Run Bandit Scan
      - name: Run Bandit Scan
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          bandit -r .
          
      # Push to Test Repo
      - name: Push to Test Repo
        run: |
          git remote add test-repo https://github.com/Khaanvani-Org/test.git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Automated commit: Bandit scan results"
          git push test-repo main
        env:
          GH_TOKEN: ${{ secrets.ALLPERMS }}
